// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTA7CU3_EKIf3lnrMGApV5lmFTTWmn_ko',
    appId: '1:281226906760:web:5f76bd018c75cdc14b633d',
    messagingSenderId: '281226906760',
    projectId: 'todo-app-e0f7d',
    authDomain: 'todo-app-e0f7d.firebaseapp.com',
    storageBucket: 'todo-app-e0f7d.appspot.com',
    measurementId: 'G-BEH4QJWNL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCICO1nuTbEm4GLTebENL9eNoHGEz51eMc',
    appId: '1:281226906760:android:4b1235962fd27db94b633d',
    messagingSenderId: '281226906760',
    projectId: 'todo-app-e0f7d',
    storageBucket: 'todo-app-e0f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlTbGyLBNcxovQLtZQtkD44UOstHAz4PY',
    appId: '1:281226906760:ios:292cd9949f7bd51e4b633d',
    messagingSenderId: '281226906760',
    projectId: 'todo-app-e0f7d',
    storageBucket: 'todo-app-e0f7d.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
